# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    cache: cache_resolver_aws_s3
    loaders:
        loader_aws_s3:
            stream:
                wrapper: gaufrette://filesystem_store_photos/
    driver: "gd"
    # configure resolvers
    resolvers :
        cache_resolver_aws_s3:
            aws_s3:
                client_config:
                    credentials:
                        key:    "%env(AWS_KEY)%"
                        secret: "%env(AWS_SECRET)%"
                    region: "%env(AWS_REGION)%"
                    version: "latest"
                bucket: "%env(AWS_BUCKET_NAME)%"
                get_options:
                    Scheme: 'https'
                put_options:
                    CacheControl: 'max-age=86400'

            # setup the default resolver
            #default :

            # use the default web path
            #web_path : ~

    # your filter sets are defined here
    filter_sets :

        # use the default cache configuration
        #cache : ~

        my_thumb :
            quality : 75
            cache: cache_resolver_aws_s3
            data_loader: loader_aws_s3
            filters:
                thumbnail : {size: [800, 553], mode: outbound, allow_upscale: true}
        xs_thumb :
            quality : 75
            cache: cache_resolver_aws_s3
            data_loader: loader_aws_s3
            filters:
                thumbnail : {size: [50, 50], mode: outbound }
        profile_pic :
            quality : 75
            cache: cache_resolver_aws_s3
            data_loader: loader_aws_s3
            filters:
                thumbnail : {size: [200, 200], mode: outbound }