vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: filesystem_store_photos
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
